/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type CredentialsStruct = {
  to: PromiseOrValue<string>;
  call: PromiseOrValue<BytesLike>;
  timestamp: PromiseOrValue<BigNumberish>;
  approvals: PromiseOrValue<BytesLike>[];
};

export type CredentialsStructOutput = [string, string, BigNumber, string[]] & {
  to: string;
  call: string;
  timestamp: BigNumber;
  approvals: string[];
};

export interface WalletExampleInterface extends utils.Interface {
  functions: {
    "burn((address,bytes,uint256,bytes[]))": FunctionFragment;
    "protectedWithdraw(uint256,(address,bytes,uint256,bytes[]))": FunctionFragment;
    "unprotectedWithdraw(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "burn" | "protectedWithdraw" | "unprotectedWithdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "burn",
    values: [CredentialsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "protectedWithdraw",
    values: [PromiseOrValue<BigNumberish>, CredentialsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "unprotectedWithdraw",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protectedWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unprotectedWithdraw",
    data: BytesLike
  ): Result;

  events: {
    "IsShieldable(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "IsShieldable"): EventFragment;
}

export interface IsShieldableEventObject {
  c: string;
}
export type IsShieldableEvent = TypedEvent<[string], IsShieldableEventObject>;

export type IsShieldableEventFilter = TypedEventFilter<IsShieldableEvent>;

export interface WalletExample extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WalletExampleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    burn(
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    protectedWithdraw(
      amount: PromiseOrValue<BigNumberish>,
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unprotectedWithdraw(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  burn(
    credentials: CredentialsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  protectedWithdraw(
    amount: PromiseOrValue<BigNumberish>,
    credentials: CredentialsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unprotectedWithdraw(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    burn(
      credentials: CredentialsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    protectedWithdraw(
      amount: PromiseOrValue<BigNumberish>,
      credentials: CredentialsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    unprotectedWithdraw(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "IsShieldable(address)"(c?: null): IsShieldableEventFilter;
    IsShieldable(c?: null): IsShieldableEventFilter;
  };

  estimateGas: {
    burn(
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    protectedWithdraw(
      amount: PromiseOrValue<BigNumberish>,
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unprotectedWithdraw(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    burn(
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    protectedWithdraw(
      amount: PromiseOrValue<BigNumberish>,
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unprotectedWithdraw(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
