/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WalletExample } from "./WalletExample";
export type { WalletExampleWithoutShield } from "./WalletExampleWithoutShield";
