/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { WalletExample__factory } from "./WalletExample__factory";
export { WalletExampleWithShield__factory } from "./WalletExampleWithShield__factory";
