"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.Shieldable__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "string",
                name: "reason",
                type: "string"
            },
        ],
        name: "InvalidCredentials",
        type: "error"
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "shieldable",
                type: "address"
            },
            {
                indexed: false,
                internalType: "address",
                name: "shield",
                type: "address"
            },
        ],
        name: "ShieldableDeployed",
        type: "event"
    },
];
var Shieldable__factory = /** @class */ (function () {
    function Shieldable__factory() {
    }
    Shieldable__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Shieldable__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Shieldable__factory.abi = _abi;
    return Shieldable__factory;
}());
exports.Shieldable__factory = Shieldable__factory;
