/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { WalletExample__factory } from "./WalletExample__factory";
export { WalletExampleWithoutShield__factory } from "./WalletExampleWithoutShield__factory";
