/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  PayableOverrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  WalletExampleWithoutShield,
  WalletExampleWithoutShieldInterface,
} from "../../../contracts/WalletExampleWithoutShield.sol/WalletExampleWithoutShield";

const _abi = [
  {
    inputs: [],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052600080546001600160a01b0319163317905560d4806100246000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80632e1a7d4d14602d575b600080fd5b603c60383660046084565b603e565b005b6000546001600160a01b03163314605457600080fd5b604051339082156108fc029083906000818181858888f193505050501580156080573d6000803e3d6000fd5b5050565b6000602082840312156097576097600080fd5b503591905056fea26469706673582212208f7ac4a8d91170214d7b0242dae3746ccd848c34e49552f5f19f9c54821d68bc64736f6c63430008110033";

type WalletExampleWithoutShieldConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: WalletExampleWithoutShieldConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class WalletExampleWithoutShield__factory extends ContractFactory {
  constructor(...args: WalletExampleWithoutShieldConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<WalletExampleWithoutShield> {
    return super.deploy(overrides || {}) as Promise<WalletExampleWithoutShield>;
  }
  override getDeployTransaction(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): WalletExampleWithoutShield {
    return super.attach(address) as WalletExampleWithoutShield;
  }
  override connect(signer: Signer): WalletExampleWithoutShield__factory {
    return super.connect(signer) as WalletExampleWithoutShield__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): WalletExampleWithoutShieldInterface {
    return new utils.Interface(_abi) as WalletExampleWithoutShieldInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): WalletExampleWithoutShield {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as WalletExampleWithoutShield;
  }
}
