/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WalletCompanion } from "./WalletCompanion";
export type { WalletExampleWithoutShield } from "./WalletExampleWithoutShield";
