"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.WalletExampleWithoutShield__factory = exports.WalletExampleWithShield__factory = exports.ShieldFactory__factory = exports.shieldSol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.shieldSol = require("./Shield.sol");
var ShieldFactory__factory_1 = require("./ShieldFactory__factory");
__createBinding(exports, ShieldFactory__factory_1, "ShieldFactory__factory");
var WalletExampleWithShield__factory_1 = require("./WalletExampleWithShield__factory");
__createBinding(exports, WalletExampleWithShield__factory_1, "WalletExampleWithShield__factory");
var WalletExampleWithoutShield__factory_1 = require("./WalletExampleWithoutShield__factory");
__createBinding(exports, WalletExampleWithoutShield__factory_1, "WalletExampleWithoutShield__factory");
