/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as shieldSol from "./Shield.sol";
export { ShieldFactory__factory } from "./ShieldFactory__factory";
export { WalletExampleWithShield__factory } from "./WalletExampleWithShield__factory";
export { WalletExampleWithoutShield__factory } from "./WalletExampleWithoutShield__factory";
