"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
exports.__esModule = true;
exports.WalletExampleWithoutShield__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        stateMutability: "payable",
        type: "constructor"
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "amount",
                type: "uint256"
            },
        ],
        name: "withdraw",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function"
    },
];
var _bytecode = "0x6080604052600080546001600160a01b03191633179055610127806100256000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80632e1a7d4d14602d575b600080fd5b603c603836600460c5565b603e565b005b6000546001600160a01b03163314605457600080fd5b6000336001600160a01b031682604051606b9060ea565b60006040518083038185875af1925050503d806000811460a6576040519150601f19603f3d011682016040523d82523d6000602084013e60ab565b606091505b505090508060b857600080fd5b5050565b80355b92915050565b60006020828403121560d85760d8600080fd5b600060e2848460bc565b949350505050565b60008160bf56fea264697066735822122074d5d0d26db09267b13e56f56f064d399e7d2cb292aafb051b32afd1891cdbfd64736f6c63430008110033";
var isSuperArgs = function (xs) { return xs.length > 1; };
var WalletExampleWithoutShield__factory = /** @class */ (function (_super) {
    __extends(WalletExampleWithoutShield__factory, _super);
    function WalletExampleWithoutShield__factory() {
        var args = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            args[_i] = arguments[_i];
        }
        var _this = this;
        if (isSuperArgs(args)) {
            _this = _super.apply(this, args) || this;
        }
        else {
            _this = _super.call(this, _abi, _bytecode, args[0]) || this;
        }
        return _this;
    }
    WalletExampleWithoutShield__factory.prototype.deploy = function (overrides) {
        return _super.prototype.deploy.call(this, overrides || {});
    };
    WalletExampleWithoutShield__factory.prototype.getDeployTransaction = function (overrides) {
        return _super.prototype.getDeployTransaction.call(this, overrides || {});
    };
    WalletExampleWithoutShield__factory.prototype.attach = function (address) {
        return _super.prototype.attach.call(this, address);
    };
    WalletExampleWithoutShield__factory.prototype.connect = function (signer) {
        return _super.prototype.connect.call(this, signer);
    };
    WalletExampleWithoutShield__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    WalletExampleWithoutShield__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    WalletExampleWithoutShield__factory.bytecode = _bytecode;
    WalletExampleWithoutShield__factory.abi = _abi;
    return WalletExampleWithoutShield__factory;
}(ethers_1.ContractFactory));
exports.WalletExampleWithoutShield__factory = WalletExampleWithoutShield__factory;
