/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ShieldableInterface extends utils.Interface {
  functions: {};

  events: {
    "ShieldableDeployed(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ShieldableDeployed"): EventFragment;
}

export interface ShieldableDeployedEventObject {
  shieldable: string;
  shield: string;
}
export type ShieldableDeployedEvent = TypedEvent<
  [string, string],
  ShieldableDeployedEventObject
>;

export type ShieldableDeployedEventFilter =
  TypedEventFilter<ShieldableDeployedEvent>;

export interface Shieldable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ShieldableInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "ShieldableDeployed(address,address)"(
      shieldable?: null,
      shield?: null
    ): ShieldableDeployedEventFilter;
    ShieldableDeployed(
      shieldable?: null,
      shield?: null
    ): ShieldableDeployedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
