/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type CredentialsStruct = {
  to: PromiseOrValue<string>;
  timestamp: PromiseOrValue<BigNumberish>;
  call: PromiseOrValue<BytesLike>;
  approvals: PromiseOrValue<BytesLike>[];
};

export type CredentialsStructOutput = [string, BigNumber, string, string[]] & {
  to: string;
  timestamp: BigNumber;
  call: string;
  approvals: string[];
};

export type UserStruct = {
  addr: PromiseOrValue<string>;
  roles: PromiseOrValue<BytesLike>;
};

export type UserStructOutput = [string, string] & {
  addr: string;
  roles: string;
};

export interface ShieldInterface extends utils.Interface {
  functions: {
    "addPolicy(bytes32,bytes8[],(address,uint256,bytes,bytes[]))": FunctionFragment;
    "addRoles(bytes32[],(address,uint256,bytes,bytes[]))": FunctionFragment;
    "assignPolicy(address,bytes4,bytes32,(address,uint256,bytes,bytes[]))": FunctionFragment;
    "burnCredentials((address,uint256,bytes,bytes[]))": FunctionFragment;
    "getAssignedPolicy(address,bytes4)": FunctionFragment;
    "getPolicy(bytes32)": FunctionFragment;
    "getRoles()": FunctionFragment;
    "getUser(address)": FunctionFragment;
    "initialize(address,bytes32[],(address,bytes8)[],bytes8[])": FunctionFragment;
    "pause((address,uint256,bytes,bytes[]))": FunctionFragment;
    "paused()": FunctionFragment;
    "setUser(address,bytes8,(address,uint256,bytes,bytes[]))": FunctionFragment;
    "transfer(address,uint256,(address,uint256,bytes,bytes[]))": FunctionFragment;
    "unpause((address,uint256,bytes,bytes[]))": FunctionFragment;
    "validateCredentials((address,uint256,bytes,bytes[]),address,address,bytes4,bytes,bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addPolicy"
      | "addRoles"
      | "assignPolicy"
      | "burnCredentials"
      | "getAssignedPolicy"
      | "getPolicy"
      | "getRoles"
      | "getUser"
      | "initialize"
      | "pause"
      | "paused"
      | "setUser"
      | "transfer"
      | "unpause"
      | "validateCredentials"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addPolicy",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>[],
      CredentialsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addRoles",
    values: [PromiseOrValue<BytesLike>[], CredentialsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "assignPolicy",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      CredentialsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "burnCredentials",
    values: [CredentialsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssignedPolicy",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicy",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "getRoles", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>[],
      UserStruct[],
      PromiseOrValue<BytesLike>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "pause",
    values: [CredentialsStruct]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setUser",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      CredentialsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      CredentialsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "unpause",
    values: [CredentialsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "validateCredentials",
    values: [
      CredentialsStruct,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "addPolicy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addRoles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assignPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssignedPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPolicy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRoles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateCredentials",
    data: BytesLike
  ): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "Paused()": EventFragment;
    "PolicyAdded(bytes32,bytes8[])": EventFragment;
    "PolicyAssigned(address,bytes4,bytes32)": EventFragment;
    "RolesAdded(bytes32[])": EventFragment;
    "ShieldableDeployed(address,address)": EventFragment;
    "Unpaused()": EventFragment;
    "UserSet(address,bytes8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PolicyAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PolicyAssigned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RolesAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ShieldableDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserSet"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface PausedEventObject {}
export type PausedEvent = TypedEvent<[], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface PolicyAddedEventObject {
  label: string;
  policy: string[];
}
export type PolicyAddedEvent = TypedEvent<
  [string, string[]],
  PolicyAddedEventObject
>;

export type PolicyAddedEventFilter = TypedEventFilter<PolicyAddedEvent>;

export interface PolicyAssignedEventObject {
  to: string;
  sig: string;
  label: string;
}
export type PolicyAssignedEvent = TypedEvent<
  [string, string, string],
  PolicyAssignedEventObject
>;

export type PolicyAssignedEventFilter = TypedEventFilter<PolicyAssignedEvent>;

export interface RolesAddedEventObject {
  roles: string[];
}
export type RolesAddedEvent = TypedEvent<[string[]], RolesAddedEventObject>;

export type RolesAddedEventFilter = TypedEventFilter<RolesAddedEvent>;

export interface ShieldableDeployedEventObject {
  shieldable: string;
  shield: string;
}
export type ShieldableDeployedEvent = TypedEvent<
  [string, string],
  ShieldableDeployedEventObject
>;

export type ShieldableDeployedEventFilter =
  TypedEventFilter<ShieldableDeployedEvent>;

export interface UnpausedEventObject {}
export type UnpausedEvent = TypedEvent<[], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface UserSetEventObject {
  user: string;
  roles: string;
}
export type UserSetEvent = TypedEvent<[string, string], UserSetEventObject>;

export type UserSetEventFilter = TypedEventFilter<UserSetEvent>;

export interface Shield extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ShieldInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addPolicy(
      label: PromiseOrValue<BytesLike>,
      policy: PromiseOrValue<BytesLike>[],
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addRoles(
      _roles: PromiseOrValue<BytesLike>[],
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    assignPolicy(
      to: PromiseOrValue<string>,
      sig: PromiseOrValue<BytesLike>,
      label: PromiseOrValue<BytesLike>,
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    burnCredentials(
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAssignedPolicy(
      to: PromiseOrValue<string>,
      sig: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getPolicy(
      label: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getRoles(overrides?: CallOverrides): Promise<[string[]]>;

    getUser(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    initialize(
      _factory: PromiseOrValue<string>,
      _roles: PromiseOrValue<BytesLike>[],
      _users: UserStruct[],
      policy: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pause(
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    setUser(
      addr: PromiseOrValue<string>,
      _roles: PromiseOrValue<BytesLike>,
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transfer(
      _to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      credentials: CredentialsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpause(
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    validateCredentials(
      credentials: CredentialsStruct,
      sender: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      f: PromiseOrValue<BytesLike>,
      call: PromiseOrValue<BytesLike>,
      full: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;
  };

  addPolicy(
    label: PromiseOrValue<BytesLike>,
    policy: PromiseOrValue<BytesLike>[],
    credentials: CredentialsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addRoles(
    _roles: PromiseOrValue<BytesLike>[],
    credentials: CredentialsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  assignPolicy(
    to: PromiseOrValue<string>,
    sig: PromiseOrValue<BytesLike>,
    label: PromiseOrValue<BytesLike>,
    credentials: CredentialsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  burnCredentials(
    credentials: CredentialsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAssignedPolicy(
    to: PromiseOrValue<string>,
    sig: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getPolicy(
    label: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getRoles(overrides?: CallOverrides): Promise<string[]>;

  getUser(
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  initialize(
    _factory: PromiseOrValue<string>,
    _roles: PromiseOrValue<BytesLike>[],
    _users: UserStruct[],
    policy: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pause(
    credentials: CredentialsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  setUser(
    addr: PromiseOrValue<string>,
    _roles: PromiseOrValue<BytesLike>,
    credentials: CredentialsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transfer(
    _to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    credentials: CredentialsStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpause(
    credentials: CredentialsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  validateCredentials(
    credentials: CredentialsStruct,
    sender: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    f: PromiseOrValue<BytesLike>,
    call: PromiseOrValue<BytesLike>,
    full: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  callStatic: {
    addPolicy(
      label: PromiseOrValue<BytesLike>,
      policy: PromiseOrValue<BytesLike>[],
      credentials: CredentialsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    addRoles(
      _roles: PromiseOrValue<BytesLike>[],
      credentials: CredentialsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    assignPolicy(
      to: PromiseOrValue<string>,
      sig: PromiseOrValue<BytesLike>,
      label: PromiseOrValue<BytesLike>,
      credentials: CredentialsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    burnCredentials(
      credentials: CredentialsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    getAssignedPolicy(
      to: PromiseOrValue<string>,
      sig: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getPolicy(
      label: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getRoles(overrides?: CallOverrides): Promise<string[]>;

    getUser(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(
      _factory: PromiseOrValue<string>,
      _roles: PromiseOrValue<BytesLike>[],
      _users: UserStruct[],
      policy: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    pause(
      credentials: CredentialsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    setUser(
      addr: PromiseOrValue<string>,
      _roles: PromiseOrValue<BytesLike>,
      credentials: CredentialsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    transfer(
      _to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      credentials: CredentialsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(
      credentials: CredentialsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    validateCredentials(
      credentials: CredentialsStruct,
      sender: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      f: PromiseOrValue<BytesLike>,
      call: PromiseOrValue<BytesLike>,
      full: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<string[]>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "Paused()"(): PausedEventFilter;
    Paused(): PausedEventFilter;

    "PolicyAdded(bytes32,bytes8[])"(
      label?: PromiseOrValue<BytesLike> | null,
      policy?: null
    ): PolicyAddedEventFilter;
    PolicyAdded(
      label?: PromiseOrValue<BytesLike> | null,
      policy?: null
    ): PolicyAddedEventFilter;

    "PolicyAssigned(address,bytes4,bytes32)"(
      to?: PromiseOrValue<string> | null,
      sig?: null,
      label?: PromiseOrValue<BytesLike> | null
    ): PolicyAssignedEventFilter;
    PolicyAssigned(
      to?: PromiseOrValue<string> | null,
      sig?: null,
      label?: PromiseOrValue<BytesLike> | null
    ): PolicyAssignedEventFilter;

    "RolesAdded(bytes32[])"(roles?: null): RolesAddedEventFilter;
    RolesAdded(roles?: null): RolesAddedEventFilter;

    "ShieldableDeployed(address,address)"(
      shieldable?: null,
      shield?: null
    ): ShieldableDeployedEventFilter;
    ShieldableDeployed(
      shieldable?: null,
      shield?: null
    ): ShieldableDeployedEventFilter;

    "Unpaused()"(): UnpausedEventFilter;
    Unpaused(): UnpausedEventFilter;

    "UserSet(address,bytes8)"(user?: null, roles?: null): UserSetEventFilter;
    UserSet(user?: null, roles?: null): UserSetEventFilter;
  };

  estimateGas: {
    addPolicy(
      label: PromiseOrValue<BytesLike>,
      policy: PromiseOrValue<BytesLike>[],
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addRoles(
      _roles: PromiseOrValue<BytesLike>[],
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    assignPolicy(
      to: PromiseOrValue<string>,
      sig: PromiseOrValue<BytesLike>,
      label: PromiseOrValue<BytesLike>,
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    burnCredentials(
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAssignedPolicy(
      to: PromiseOrValue<string>,
      sig: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPolicy(
      label: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoles(overrides?: CallOverrides): Promise<BigNumber>;

    getUser(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _factory: PromiseOrValue<string>,
      _roles: PromiseOrValue<BytesLike>[],
      _users: UserStruct[],
      policy: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pause(
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    setUser(
      addr: PromiseOrValue<string>,
      _roles: PromiseOrValue<BytesLike>,
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transfer(
      _to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      credentials: CredentialsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpause(
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    validateCredentials(
      credentials: CredentialsStruct,
      sender: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      f: PromiseOrValue<BytesLike>,
      call: PromiseOrValue<BytesLike>,
      full: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addPolicy(
      label: PromiseOrValue<BytesLike>,
      policy: PromiseOrValue<BytesLike>[],
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addRoles(
      _roles: PromiseOrValue<BytesLike>[],
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    assignPolicy(
      to: PromiseOrValue<string>,
      sig: PromiseOrValue<BytesLike>,
      label: PromiseOrValue<BytesLike>,
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    burnCredentials(
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAssignedPolicy(
      to: PromiseOrValue<string>,
      sig: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPolicy(
      label: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoles(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUser(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _factory: PromiseOrValue<string>,
      _roles: PromiseOrValue<BytesLike>[],
      _users: UserStruct[],
      policy: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pause(
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setUser(
      addr: PromiseOrValue<string>,
      _roles: PromiseOrValue<BytesLike>,
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transfer(
      _to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      credentials: CredentialsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      credentials: CredentialsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    validateCredentials(
      credentials: CredentialsStruct,
      sender: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      f: PromiseOrValue<BytesLike>,
      call: PromiseOrValue<BytesLike>,
      full: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
