/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "Shield",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Shield__factory>;
    getContractFactory(
      name: "Shieldable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Shieldable__factory>;
    getContractFactory(
      name: "ShieldFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ShieldFactory__factory>;
    getContractFactory(
      name: "WalletExampleWithoutShield",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WalletExampleWithoutShield__factory>;
    getContractFactory(
      name: "WalletExampleWithShield",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WalletExampleWithShield__factory>;

    getContractAt(
      name: "Initializable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "Shield",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Shield>;
    getContractAt(
      name: "Shieldable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Shieldable>;
    getContractAt(
      name: "ShieldFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ShieldFactory>;
    getContractAt(
      name: "WalletExampleWithoutShield",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WalletExampleWithoutShield>;
    getContractAt(
      name: "WalletExampleWithShield",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WalletExampleWithShield>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
