/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { WalletCompanion__factory } from "./WalletCompanion__factory";
export { WalletExampleWithoutShield__factory } from "./WalletExampleWithoutShield__factory";
